# https://github.com/pages-themes/cayman
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
# title: Test Jekyll title
# description: Test Jekyll desc
# show_downloads: false
# google_analytics: G-3FS8BQFQRG
